set nocompatible              " be iMproved, required
filetype off                  " required

""" My settings
syn on
set number
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
set expandtab
set list
au BufRead *.md setlocal spell
au BufRead *.md setlocal wrap
set path+=$PWD/**