# /Users/josh/.config/tmuxinator/voltron.yml
name: voltron
root: ~/
windows:
  - madhax:
      layout: 2c93,270x65,0,0[270x47,0,0{160x47,0,0,11,109x47,161,0,21},270x17,0,48{135x17,0,48,19,134x17,136,48,20}]
      panes:
        - 
        - voltron view disasm
        - voltron view bt
        - voltron view bp
